В данном репозитории преставленно 2 .py файла, в фале "init" написаны все функции, а в файле "Check_test" представлены тесты.
Честно признаться, на моем устройстве все вызовы функций PUT и POST вызывали ошибку с кодом 500, что говорит о проблеме на сервере. (Хотя, конечно, ошибка может быть и в коде)
Буду рад, если на вашем устройстве этой ошибки не будет, ведь половина моего кода рассчитана именно на это. Буду ждать результатов и/или вопросов по работе. Спасибо!
